audit_header: false
title: Bay Area Real Estate Video Blog with Greg McDaniel
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Radio Show
    url: http://www.kgoradio.com/real-estate-radio-talk/
  - title: 360 Videos
    url: /360-videos

client:
  name: Greg McDaniel
  title:
  license_number:
  about_markdown: |
    With over 70 years real estate experience between the three partners, McDaniel Callahan TEAM has helped over 1800 families buy or sell a Bay area home. That level of experience means McDaniel Callahan can sell your Bay area home for more money in less time, and help you find your dream home at the best price and terms.

    Featuring a strong administrative team that handles all the critical details of every transaction, and availability of all three partners to each client, McDaniel Callahan can make your move a stress-free experience.
  market: Bay Area
  brand: McDaniel Callahan TEAM
  brokerage: eXp Realty
  address: 144 Irongate Court.<br>Alamo, CA 94507
  phone: 925-838-4300
  phone_type:
  phone2:
  phone2_type:
  email: TEAM@mcdanielcallahan.com
  url: https://www.mcdanielcallahan.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://cloudcma.com/api_widget/6757802779fbc05a66bfd8f78d617a92/show?post_url=cloudcma.com&source_url=ua
  second_CTA_text: Home Search
  second_CTA_URL: http://www.buyandsellalamodanvillehomes.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://cloudcma.com/api_widget/6757802779fbc05a66bfd8f78d617a92/show?post_url=cloudcma.com&source_url=ua

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.buyandsellalamodanvillehomes.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/pages/McDaniel-Callahan-Real-Estate-Team/191018390914223
  linkedin_url: http://www.linkedin.com/pub/mcdaniel-callahan-team/80/184/a94
  gplus_url: https://plus.google.com/117894637475105854403
  youtube_url: https://www.youtube.com/user/mcdanielcallahan/featured
  twitter_url: https://twitter.com/alamorealestate
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/mcdanielcallahan3/
  trulia_url: http://www.trulia.com/profile/mcdaniel-callahan-team-agent-danville-ca-55580/overview
  yelp_url: http://www.yelp.com/biz/mcdaniel-callahan-danville
  podcast_url: https://itunes.apple.com/us/podcast/bay-area-real-estate-podcast-with-greg-mcdaniels/id916247125?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
